name: Linux Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.17]
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build test binary
      run: go test -c -race

    # These tests run on Linux only. Apply capabilities and verify we can
    # actually use real AF_KCM sockets.
    - name: Apply CAP_NET_RAW
      run: sudo setcap cap_bpf+ep ./kcm.test

    - name: Run tests with capabilities
      run: ./kcm.test -test.v
